// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CheckoutBranch(arg1:string):Promise<main.CheckoutResult>;

export function CloneRepo(arg1:string,arg2:string):Promise<main.CloneResult>;

export function Commit(arg1:string,arg2:string):Promise<main.CommitResult>;

export function CreateRepo(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:string,arg6:string,arg7:string):Promise<main.CreateRepoResult>;

export function DeleteRepo(arg1:string,arg2:string):Promise<main.DeleteResult>;

export function DownloadUpdate():Promise<Record<string, any>>;

export function Fetch():Promise<main.FetchResult>;

export function GetBranchInfo():Promise<main.BranchInfoResult>;

export function GetBranches():Promise<Array<string>>;

export function GetCachedRepos():Promise<Array<Record<string, any>>>;

export function GetChanges():Promise<main.ChangesResult>;

export function GetCommitDiff(arg1:string):Promise<main.CommitDiffResult>;

export function GetConfig():Promise<Record<string, any>>;

export function GetCurrentUser():Promise<string>;

export function GetDiff(arg1:string):Promise<main.DiffResult>;

export function GetGitIgnoreTemplates():Promise<Array<string>>;

export function GetHistory():Promise<Array<main.CommitInfo>>;

export function GetLastClonePath():Promise<string>;

export function GetLocalPath():Promise<string>;

export function GetRepos():Promise<main.ReposResult>;

export function GetSavedRepoPath(arg1:string):Promise<string>;

export function GetSavedToken():Promise<string>;

export function GetVersion():Promise<string>;

export function Login(arg1:string):Promise<main.LoginResult>;

export function Logout():Promise<Record<string, any>>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenInFiles(arg1:string):Promise<Record<string, any>>;

export function OpenLocalRepo(arg1:string):Promise<main.OpenRepoResult>;

export function Push():Promise<main.PushResult>;

export function SaveConfigKey(arg1:string,arg2:any):Promise<Record<string, any>>;

export function StartWatcher():Promise<Record<string, any>>;

export function StopWatcher():Promise<Record<string, any>>;
