// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckoutBranch(arg1) {
  return window['go']['main']['App']['CheckoutBranch'](arg1);
}

export function CheckoutPullRequest(arg1, arg2) {
  return window['go']['main']['App']['CheckoutPullRequest'](arg1, arg2);
}

export function CloneRepo(arg1, arg2) {
  return window['go']['main']['App']['CloneRepo'](arg1, arg2);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function CreateRepo(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateRepo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteRepo(arg1, arg2) {
  return window['go']['main']['App']['DeleteRepo'](arg1, arg2);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function Fetch() {
  return window['go']['main']['App']['Fetch']();
}

export function GetBranchInfo() {
  return window['go']['main']['App']['GetBranchInfo']();
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetCachedRepos() {
  return window['go']['main']['App']['GetCachedRepos']();
}

export function GetChanges() {
  return window['go']['main']['App']['GetChanges']();
}

export function GetCommitDiff(arg1) {
  return window['go']['main']['App']['GetCommitDiff'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConflictBlocks(arg1) {
  return window['go']['main']['App']['GetConflictBlocks'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDiff(arg1) {
  return window['go']['main']['App']['GetDiff'](arg1);
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFileTree() {
  return window['go']['main']['App']['GetFileTree']();
}

export function GetGitIgnoreTemplates() {
  return window['go']['main']['App']['GetGitIgnoreTemplates']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetLastClonePath() {
  return window['go']['main']['App']['GetLastClonePath']();
}

export function GetLocalPath() {
  return window['go']['main']['App']['GetLocalPath']();
}

export function GetPullRequests() {
  return window['go']['main']['App']['GetPullRequests']();
}

export function GetReadme() {
  return window['go']['main']['App']['GetReadme']();
}

export function GetRemoteFileContent(arg1) {
  return window['go']['main']['App']['GetRemoteFileContent'](arg1);
}

export function GetRemoteFileContentBase64(arg1) {
  return window['go']['main']['App']['GetRemoteFileContentBase64'](arg1);
}

export function GetRemoteFileTree() {
  return window['go']['main']['App']['GetRemoteFileTree']();
}

export function GetRemoteHistory() {
  return window['go']['main']['App']['GetRemoteHistory']();
}

export function GetRemoteReadme() {
  return window['go']['main']['App']['GetRemoteReadme']();
}

export function GetRepos() {
  return window['go']['main']['App']['GetRepos']();
}

export function GetSavedRepoPath(arg1) {
  return window['go']['main']['App']['GetSavedRepoPath'](arg1);
}

export function GetSavedToken() {
  return window['go']['main']['App']['GetSavedToken']();
}

export function GetStashes() {
  return window['go']['main']['App']['GetStashes']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OAuthLogin() {
  return window['go']['main']['App']['OAuthLogin']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenInFiles(arg1) {
  return window['go']['main']['App']['OpenInFiles'](arg1);
}

export function OpenLocalRepo(arg1) {
  return window['go']['main']['App']['OpenLocalRepo'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Push() {
  return window['go']['main']['App']['Push']();
}

export function ResolveConflict(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2);
}

export function SaveConfigKey(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigKey'](arg1, arg2);
}

export function SetCurrentRepo(arg1) {
  return window['go']['main']['App']['SetCurrentRepo'](arg1);
}

export function StartWatcher() {
  return window['go']['main']['App']['StartWatcher']();
}

export function Stash() {
  return window['go']['main']['App']['Stash']();
}

export function StashDrop(arg1) {
  return window['go']['main']['App']['StashDrop'](arg1);
}

export function StashPop(arg1) {
  return window['go']['main']['App']['StashPop'](arg1);
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
